# Generated by Django 4.2.4 on 2023-10-31 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email',models.CharField(default='',max_length=20)),
                ('contact',models.ImageField(default='',max_length=10)),
            ],
        ),
    ]
